@url=http://localhost:3000
@json=Content-Type: application/json 
POST {{url}}/admin/api/register
{{json}}

{
    "username":"admin",
    "password":"wxq000131",
    "captcha":"15"
}
###
POST {{url}}/admin/api/login
{{json}}

{
    "username":"admin",
    "password":"wxq000131"
}

###
GET {{url}}/admin/api/captcha
