@url=http://localhost:3000
@json=Content-Type: application/json 
POST {{url}}/admin/api/article
{{json}}

{
    "title":"first",
    "content":"+"
}

###
GET {{url}}/web/api/comment/60e50b07e3cec7081006fa65
